Bug/sw 5 10/26 test addmeals fix
aau-giraf/foodplanner-api pull request #128
Opened 2024-12-09 14:38 UTC by alexaaskov

# Description

*Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.*

Fixes #\<issue_no>

## Type of change
*Delete unchecked boxes (only for Type of change)*

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration*

**Development Configuration**
*Type "flutter --version" and "dart --version" in your CMD to check versions.*

* Flutter version:
* Dart version:

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas, if necessary
- [ ] I have made corresponding changes to the documentation, if necessary
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works, if necessary
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [ ] I have Acceptance Tested this on an iOS device
- [ ] I have Acceptance Tested this on an Android device

2025-09-17 10:27 UTC, lindejacob requested changes

2025-09-17 10:27 UTC, lindejacob commented on FoodplannerApi/Controller/ImagesController.cs
> +        }
Why not use linq here? It would make it more readable to use linq. Linq is also a more common occurrence in the project

2025-09-17 10:27 UTC, lindejacob commented on FoodplannerModels/Lunchbox/Ingredient/IIngredientService.cs
> +    Task<Ingredient?> GetIngredientByIdAsync(int id);
Why is this nullable, dont you wan't a error?

2025-09-17 10:27 UTC, lindejacob commented on FoodplannerModels/Lunchbox/Meal/IMealService.cs
> +    Task<MealDTO?> GetMealByIdAsync(int id);
Why is this nullable, dont you wan't a error?

2025-09-17 10:27 UTC, lindejacob commented on FoodplannerModels/Lunchbox/PackedIngredient/IPackedIngredientService.cs
> +    Task<PackedIngredient?> GetPackedIngredientByIdAsync(int id);
Why is this nullable, dont you wan't a error?

2025-09-17 10:27 UTC, lindejacob commented on FoodplannerApi/Controller/ImagesController.cs
> +            else
If there is going to be another commit.... Please remove this space

2025-09-17 10:27 UTC, lindejacob commented on FoodplannerServices/Lunchbox/IngredientService.cs
> +    public async Task<Ingredient?> GetIngredientByIdAsync(int id)
Why is this nullable, dont you wan't a error?

2025-09-17 10:27 UTC, lindejacob commented on Test/AccountTests/Controller/ChildrenControllerTest.cs
> +        var children = new List<ChildrenGetAllDTO> {
This needs to be rewritten when a testing factory is implemented, with the child values,

2025-09-22 10:40 UTC, lindejacob requested changes

2025-09-22 10:40 UTC, lindejacob commented on FoodplannerApi/Controller/ImagesController.cs
>          }
Do this in linq

2025-09-22 10:40 UTC, lindejacob commented on FoodplannerApi/Controller/ImagesController.cs
> +
`if(!foodImageId)
{ throw new Exception("FoodImageId is null"); }`

2025-09-22 10:40 UTC, lindejacob commented on FoodplannerServices/Lunchbox/MealService.cs
> +    public async Task<MealDTO?> GetMealByIdAsync(int id)
Avoid using nullable, research to see if there is an actual other alternative. This is also true for the other places.

2025-09-22 10:40 UTC, lindejacob commented on FoodplannerServices/Lunchbox/PackedIngredientService.cs
> +        public async Task<PackedIngredient?> GetPackedIngredientByIdAsync(int id)
Avoid using nullable, research to see if there is an actual other alternative. This is also true for the other places.

2025-09-22 20:26 UTC, lindejacob submitted a review, later dismissed

2025-09-22 20:26 UTC, lindejacob commented on Test/AccountTests/Controller/UsersControllerTest.cs
> +        var userCreateDto = new UserCreateDTO
Why create the DTO? Not the user

2025-09-22 20:26 UTC, lindejacob commented on Test/LunchboxTests/Controller/PackedIngredientsControllerTest.cs
> +        PackedIngredientProperDTO packedIngredientDTO = new() { Ingredient_id = ingredientId, Meal_id = mealId};
Why create the DTO instead of the object?

2025-09-22 20:26 UTC, lindejacob commented on Test/LunchboxTests/Controller/PackedIngredientsControllerTest.cs
> +        PackedIngredientProperDTO packedIngredientDTO = new() { Ingredient_id = ingredientId, Meal_id = mealId};
Why create the DTO instead of the object?

2025-09-22 20:26 UTC, lindejacob commented on Test/LunchboxTests/Service/IngredientServiceTests.cs
> +        var result = await ingredientService.CreateIngredientAsync(new IngredientDTO { Name = "Onion", Food_image_id = 2 }, 2);
Why create the DTO instead of the object?

2025-09-22 20:26 UTC, lindejacob commented on Test/LunchboxTests/Service/IngredientServiceTests.cs
> +        var exception = await Assert.ThrowsAsync<ArgumentException>(() => ingredientService.CreateIngredientAsync(new IngredientDTO { Name = null, Food_image_id = 2 }, 2));
Why create the DTO instead of the object?Why create the DTO instead of the object?

2025-09-22 20:26 UTC, lindejacob commented on Test/LunchboxTests/Service/MealServiceTests.cs
> +        var mealCreateDTO = new MealCreateDTO { Name = "Salad", Date = "21/03/2023" };
Why create the DTO instead of the object?

2025-09-22 20:26 UTC, lindejacob commented on Test/LunchboxTests/Service/PackedIngredientServiceTests.cs
> +            new PackedIngredientDTO { Id = 2, Meal_id = mealId, Ingredient_id = new Ingredient{ Id = 1, Name = "rottests", User_id = 2 }, order_number = 2 }
Why create the DTO instead of the object?

2025-09-29 07:40 UTC, lindejacob commented on FoodplannerApi/Controller/ImagesController.cs
> +
This is still missing

2025-11-03 08:49 UTC, MeisterRepsak approved these changes
We ball

2025-11-03 08:49 UTC, merged