Feature/sw5 10/26 add meals mergeable
aau-giraf/foodplanner-api pull request #78
Opened 2024-10-27 09:19 UTC by alexaaskov

# Description

Three classes, Meal, Ingredient, and Packed Ingredient are added to the system with all the necessary files.

Fixes #\<issue_no>

## Type of change
*Delete unchecked boxes (only for Type of change)*

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

# How Has This Been Tested?

Unit tests were made for the repository files and unit/integration tests were made for the controller files. There was only one issue with the implementation of the test, where we weren't able to setup a proper fixture of the database for the tests, so we have used our database (sw5-10) as the test database. Because all tests run on the same database we had to run them sequentially to prevent conflicting queries to the database.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas, if necessary
- [X] New and existing unit tests pass locally with my changes

2024-10-27 09:20 UTC, alexaaskov commented on Test/DatabaseConnection.cs
Our Test project was not able to access the appsettings files from the FoodplannerApi, so we had to hard code the outputs from the SecretLoader file.

2024-10-28 10:01 UTC, JacobStokholms requested changes
Har ikke review tests.

2024-10-28 10:01 UTC, JacobStokholms commented on README.md
> +    "Workspace": "f687b673-33f6-49df-9d7e-e5ee1717c14e"
Skal heller ikke med på stage

2024-10-28 10:01 UTC, JacobStokholms commented on Test/DatabaseConnection.cs
Ja det går ikke. Den skal mockes, eller køres gennem secretloader.

2024-10-29 10:27 UTC, alexaaskov commented on FoodplannerServices/Lunchbox/MealService.cs
> +    }
Vi mener at det umiddelbart er bedre at backend sender alt data der kan være brugbart og som ikke skal være hidden, og så er det frontend der vælger hvad for noget data de vil bruge.

2024-10-29 10:29 UTC, alexaaskov commented on FoodplannerApi/Controller/IngredientsController.cs
> +    }
Lavet meal om, så den også returnerer alle ingredients der er i meal.

2024-10-29 10:30 UTC, alexaaskov commented on FoodplannerApi/Controller/MealsController.cs
> +    }
Lavet en metode for at få alle meals der tilhører en bestemt user samt har en bestemt dato.

2024-10-29 10:30 UTC, alexaaskov commented on FoodplannerApi/Controller/IngredientsController.cs
> +    }
Vi bruger den i vores tests. Har skrevet det som i kommentar i koden.

2024-10-29 10:31 UTC, alexaaskov commented on FoodplannerApi/Controller/MealsController.cs
> +    }
Vi bruger den i vores tests. Har skrevet det som i kommentar i koden.

2024-10-29 10:37 UTC, alexaaskov commented on FoodplannerApi/Controller/PackedIngredientController.cs
Det kommer an på hvordan frontend er lavet. Når frontend og backend skal koples sammen, kan man se hvor vidt en controller for packed ingredient er nørdvendig. Ind til videre tænker vi at det bliver stående som det er, hvis nu det skal bruges.

2024-10-29 10:37 UTC, alexaaskov commented on FoodplannerApi/Program.cs
> +    var password = SecretsLoader.GetSecret("DB_PASS", "/SW-5-10/");
Har fjernet det.

2024-10-29 10:38 UTC, alexaaskov commented on FoodplannerDataAccessSql/Lunchbox/PackedIngredientRepository.cs
> +        }
Vi bruger den i vores tests. Har skrevet det som i kommentar i koden.

2024-10-29 10:42 UTC, alexaaskov commented on Test/DatabaseConnection.cs
Vi kunne ikke få det til at fungere, så det er en fremtidig opgave.

2024-10-30 08:48 UTC, JakobTopholt commented on Test/DatabaseConnection.cs
> +    private static string port = "5432";
Bruh

2024-10-30 08:48 UTC, JakobTopholt commented on Test/DatabaseConnection.cs
> +    private static string password = "yjF45K#6rmRd@2RJbbLA";
Bruh

2024-10-30 08:57 UTC, alexaaskov commented on Test/DatabaseConnection.cs
> +    private static string password = "yjF45K#6rmRd@2RJbbLA";
Vi ved det, håber nogen kan få tests til at arbejde sammen med secretloader. Vi kunne ikke.

2024-10-30 10:49 UTC, alexrefshauge commented on FoodplannerServices/Lunchbox/MealService.cs
> +    }
Vi skal beslutte os for om vi kører DTO pattern eller ej, det er forvirrende hvis vi laver en blanding

2024-10-30 10:51 UTC, alexrefshauge commented on FoodplannerApi/Controller/IngredientsController.cs
> +    }
Tænker heller ikke den er nødvendig. Hvis vi beholder det skal det som minimum låses bag Admin rollen

2024-10-30 10:52 UTC, alexrefshauge commented on FoodplannerApi/Controller/MealsController.cs
> +    }
Kan det ikke mockes i stedet?

2024-11-05 08:17 UTC, alexaaskov commented on FoodplannerServices/Lunchbox/MealService.cs
> +    }
Med de nye updates til meal har vi nu sat en DTO op.

2024-11-05 08:18 UTC, alexaaskov commented on FoodplannerApi/Controller/IngredientsController.cs
> +    }
Det har vi gjort nu.

2024-11-05 08:19 UTC, alexaaskov commented on FoodplannerApi/Controller/MealsController.cs
> +    }
Hvis vi kunne få mocks til at virke, så er det en mulighed.

2024-11-20 08:20 UTC, JacobStokholms approved these changes

2024-11-20 08:22 UTC, merged