Feature/sw 5 02/61 children child class controller
aau-giraf/foodplanner-api pull request #79
Opened 2024-10-28 09:55 UTC by JacobInberg

# Description

Create a child and classroom endpoint as well as add a child to a given class, pincode for users endpoint with update, check if pincode is correct as well as check if the user has a pincode

Fixes #61 

## Type of change
*Delete unchecked boxes (only for Type of change)*

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

# How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration*

**Development Configuration**
*Type "flutter --version" and "dart --version" in your CMD to check versions.*

* Flutter version:
* Dart version:

# Checklist:

- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas, if necessary
- [ ] I have made corresponding changes to the documentation, if necessary
- [ X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, if necessary
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have Acceptance Tested this on an iOS device
- [ ] I have Acceptance Tested this on an Android device

2024-10-28 10:16 UTC, JacobStokholms requested changes

2024-10-28 10:16 UTC, JacobStokholms commented on FoodplannerApi/Controller/ChildrensController.cs
> +    }
Skal nok ikke bruge alle børn, men kun hente en klasse ad gangen

2024-10-28 10:16 UTC, JacobStokholms commented on FoodplannerModels/Account/UserCredsDTO.cs
> +    public required int Id { get; set; }
Brug JWT til at retreive ID istedet

2024-10-28 10:16 UTC, JacobStokholms commented on FoodplannerApi/Controller/UsersController.cs
> +    public async Task<IActionResult> HasPinCode(int id) {
Brug JWT til at retreive ID istedet

2024-10-28 10:16 UTC, JacobStokholms commented on FoodplannerServices/Account/UserService.cs
> +    }
Kan vi bruge Bcrypt til at cryptere pin-koden

2024-10-28 10:16 UTC, JacobStokholms commented on FoodplannerServices/Account/UserService.cs
> +    public async Task<string> GetUserByIdAndPinCodeAsync(int id, string pinCode){
BCrypt skal så også bruges her.

2024-10-30 09:47 UTC, Dressi123 commented on FoodplannerApi/Controller/ChildrensController.cs
> +    }
den skal bruges i frontend ved oprettelse af barn og her skal man bruge alle klasser.

2024-10-30 11:24 UTC, JacobInberg commented on FoodplannerServices/Account/UserService.cs
> +    public async Task<string> GetUserByIdAndPinCodeAsync(int id, string pinCode){
Er tilføjet nu

2024-10-30 11:24 UTC, JacobInberg commented on FoodplannerModels/Account/UserCredsDTO.cs
> +    public required int Id { get; set; }
Er fixet

2024-10-30 11:24 UTC, JacobInberg commented on FoodplannerApi/Controller/UsersController.cs
> +    public async Task<IActionResult> HasPinCode(int id) {
Er fixet

2024-10-30 11:24 UTC, JacobInberg commented on FoodplannerServices/Account/UserService.cs
> +    }
Er tilføjet

2024-10-30 11:25 UTC, JacobInberg commented on FoodplannerApi/Controller/ChildrensController.cs
> +    }
Skulle men den er fjernet

2024-10-30 11:46 UTC, JacobStokholms approved these changes

2024-10-30 12:36 UTC, merged